### ISSUE TITLE
Setting the small_icon: any guides?

### ISSUE THREAD

**Issue by diegoesp** [katzer/cordova-plugin-local-notifications#1644]
## Your Environment

* Plugin version: 0.9
* Platform: Android
* OS version: Android 7
* Device manufacturer / model: Moto 4G
* Cordova version (```cordova -v```): 8.0.0
* Cordova platform version (```cordova platform ls```): android 7.0.0
* Plugin config : N/A
* Ionic Version (if using Ionic): N/A

## Expected Behavior

Want to set a small icon

## Actual Behavior

I cannot set a small icon. I get a small gray circle all the time
Is there any step by step guide to set up the requirements? I've been trying to do this for hours and I don't know what to do even to debug this.

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/1253206/42739890-aeff8b2c-889f-11e8-8bd5-23a39568fc67.png)

![image](https://user-images.githubusercontent.com/1253206/42739897-b825272a-889f-11e8-9bf6-ae64d3d76ec5.png)

## Context

Setting a small icon

## Debug logs

N/A

Thanks!

**Comment by Tawpie** [comment]
Android is *very* picky about the action bar icons; be certain your icons (one for each resolution, ldpi, mdpi, hdpi, xhdpi etc) conforms _exactly_ to the android specs. One tiny mistake and you get the bell icon instead!

**Comment by diegoesp** [comment]
Thanks for your help! Do you have a link to the reqs?

**Comment by Tawpie** [comment]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_action_bar

**Comment by diegoesp** [comment]
Thanks!

**Comment by diegoesp** [comment]
OK. So, I followed the directives closely but it still showing a grey circle in the top.

Should I have a dir structure here?

![image](https://user-images.githubusercontent.com/1253206/42961111-0edf0270-8b8e-11e8-93ee-19d6cf4a7978.png)

Where can I find the dir structure that I'm supposed to put in here? I see there's  plenty of resources around the web but they contradict each other and this is very hard to debug because it simply fails without any notice.

**Comment by diegoesp** [comment]
Just FYI: I tried doing this,

![image](https://user-images.githubusercontent.com/1253206/42961331-cebb9176-8b8e-11e8-84f1-d46d1caf2b67.png)

and then this,

![image](https://user-images.githubusercontent.com/1253206/42961357-e13c556a-8b8e-11e8-808b-448e9b17fa4e.png)

but it still does not work. This is making me crazy! :)

**Comment by coffeverton** [comment]
This article helped me to get it working.

http://roblouie.com/article/273/ionic-local-notifications-part-1-the-hidden-details/

I use it like this:

```
cordova.plugins.notification.local.schedule({
                            id: id
                            ,title: title
                            ,text: text
                            ,at: data
                            ,icon: "file://images/calendar.png"
                            ,smallIcon: 'res://drawable-hdpi/ic_lembrete.png'
                            ,sound: 'file://sound/alarm.mp3'
                        });
```

**Comment by diegoesp** [comment]
Awesome. I will try it, let you know how it goes

**Comment by Tawpie** [comment]
![image](https://user-images.githubusercontent.com/7697076/42969811-415d466c-8b5c-11e8-9c2a-03bb2a36ab1b.png)
we use actionbar_dark and actionbar_light. The png are also in drawable-hdpi and drawable-xhdpi (and nowhere else)

**Comment by diegoesp** [comment]
OK, so I stripped down the app so I could fin what is the algorithm for selecting the icon doing. I think I found out, trouble is I don't have a clue on how to solve it.

There's no problem with the icon (the icon is defined as android expects). I switched the icon of the app (detailed in config.xml), changed it from the original full color icon to the transparent icon. It turns out that I can see my transparent icon now in the notification, but of course the icon of the app is also switched to the transparent icon, which looks quite ugly in my home screen.

It seems the notification is ignoring this parameter:

![image](https://user-images.githubusercontent.com/1253206/42972379-828a9f4c-8baf-11e8-8503-248ff11256dd.png)

This parameter DOES work (i.e. if I take it out I cannot see the icon on the right side of the notification):

![image](https://user-images.githubusercontent.com/1253206/42972399-946aadb0-8baf-11e8-9bcc-7469bb820bd2.png)

I tried setting smallIcon in several diferent ways, but it seems to be silently ignored, all the time :(

**Comment by Tawpie** [comment]
The small icon refers to the icon in the action bar (iOS calls it a status bar). The one to the right of the notification itself is (usually, but that depends on the phone’s android version) the app icon.

**Comment by diegoesp** [comment]
I'm 100% clear on that. The problem I'm trying to explain is that the smallIcon parameter appears to be ignored. The app seems to use the icon specified in config.xml as my small icon instead of the smallicon specified in the schedule method, all the time. "icon" in the schedule method seems to be used, though.

**Comment by rwillett** [comment]
As @Tawpie has stated, you have to set up multiple directories with the smallicon rendered at the right resolutions, thats what the screenshot shows a few comments above.

We have to copy the directories over using a hook in after_prepare at compile time to get the right icons in the right directory. Issue #1627 gives full instructions including code on how to do this.

It's not clear to me that you have setup the right notifications icons at the right size. @tawpie is 100% correct in stating Android is very picky, not just about the icon sizes and the colours within them bjt also the directories they are in.

smallicon does work as we use it in the manner shown in #1627.

Rob

**Comment by Tawpie** [comment]
@diegoesp one other thing to try is to drop the `.png` from your filename. Also, since I'm a little confused about which icon you're not seeing perhaps you could post a picture of what you're getting.

`.smallIcon = "res://actionbar_light"`

DISCLAIMER with my comments: I use pure Cordova, no Angular/Ionic frameworks so there may be framework quirks that I'm not covering!

**Comment by rwillett** [comment]
@tawpie 

We do have the .png extension so I don't think it's that. I think this may be something to do with not having the right files at compile time in the right directory. I'm not clear how other people or frameworks do it, I know you do it like we do.

**Comment by Tawpie** [comment]
here's all the smallIcons we use, their sizes and location.
![smallicons](https://user-images.githubusercontent.com/7697076/43009555-da1a59d0-8bf2-11e8-8813-d00489bee309.png)

As @rwillett mentioned, it's a good idea to copy these to the platforms directory using a hook. Every time you remove/add the android platform the contents of platforms/res is overwritten. Without a hook it's too easy to get yourself messed up.

**Comment by rwillett** [comment]
@Tawpie agreed, hooks are definitely the way to do this. 

We have a load of hooks that tidy code, simplify things and generally keep the admin out of the way.

**Comment by howlfu** [comment]
Try this to generate your smallicon, I got the same issue and fixed by below generator.
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=directions_run&source.space.trim=0&source.space.pad=0.2&name=icon

**Comment by ericpennachini** [comment]
The solution proposed by @howlfu worked for me. That is, using `resource-file` tag in **config.xml** file.
For testing purposes, I've set one icon with `hdpi` density.

**Comment by J4si3k** [comment]
I'm trying to use this plugin with Meteor by @howlfu method but still not work for me.
I'm set smallIcon to `res://icon.png`, `res://icon`, `icon`, `res://drawable-mdpi/icon.png` etc. and nothing is happen

**Comment by valdiego** [comment]
I had similar problem with "smallIcon" properties where the notification icon showed up as a "_blank white square_". I fought frustratingly for few days, and now had resolved the issue. I wrote this to share what I did.

**A. SYSTEM**
Android OS
Cordova 8.0.0

**B. DEVICES**
1. Samsung Nexus Android 4.3
2. LG G4 Android 5.1
3. Emulator Android 7.0
4. ZTE Axon Android 7.1.1
5. Samsung Tablet S3 Android 8 

**C. PROBLEM**
To all of those devices, notifications were successfully triggered and showed up, but the smallIcon showed up as "_blank white square_" icon. I believe this means: The image is not found or invalid format.

**D. ANALYSIS**
D.1. Default:  `smallIcon: "res://icon" `
This is the valid syntax we must follow (no file extension!). The default will look and use our **app icon** inside the platform's "**res** directory". As you all know, by default, Cordova will copy-paste and rename our app icon into: 
`<project>\platforms\android\app\src\main\res\mipmap-mdpi\icon.png`

However, with this default, it failed on devices 2->4. BUT it was curiously successful for device Android 4.3 (device 1) where the notification icon showed up exactly as my app icon, which is regular size 512 x 512 px.  However, there was no resizing at all such that the icon was chopped off to fit the notification icon frame. Not good.

D.2. I overwrote the default to use my own:  `smallIcon: "res://app_notification"`
This was successful for my device 4.3, but continued to fail for other devices 2->4. I tried many possible assortment of solutions. Those included: Resizing the image, providing ALL of possible sizes (mdpi, hdpi, xxhdpi, and so on), copy-pastiing to both official image sub-dirs under res (mipmap and drawable), copy-pasting to ALL possible sub-dirs under res (mipmap-mdpi, mipmap-hdpi, drawable-mdpi, drawable-hdpi, and so on), redrawing the image from color to black and white, etc. Whatever suggestions I could find online.  To all these "kitchen-sink" attempts, only my device 4.3 took them all and successfull 100%. But devices 2->4 continued to fail. Getting frustrated is an understatement (!!!)

**E. SOLUTION**
Finally I came to senses and solve this with the following
E.1. Define the property: `smallIcon: "res://app_notification"`

E.2. The image file = app_notification.png
Size = 24x24 px, Color = black-white, Format = PNG.
Yes, ONLY 1 size and it must be exact! As @Tawpie pointed out above, Android later versions are very STRICT about icon sizes. If the size is not that, it would fail and display "_blank white square_" icon. There is NO need to provide all variety of sizes. Just one image file.
REF: http://www.androiddocs.com/design/style/iconography.html#notification

E.2. Copy-paste the icon into: `<project>\platforms\android\app\src\main\res\mipmap-mdpi\`
Yes, only into this one place. This is exactly the SAME path as where Cordova build would copy-paste our app icon. Use your own build script (whatever that is) to automatically copy-paste the icon from your source code to this target path. NO need to place the icon in any variety of paths such as drawable, drawable-hdpi, etc. Just one directory.

E.3. Clear my app CACHE inside every devices
Before I redeployed my app to each device, I cleared my app cache from each device: **Setting > Apps > [My app] > Clear cache.**  I'm not sure why I had to do this on devices 2->4. Without it, some device would randomly display the same "_blank white square icon_". 

I suspected (maybe, ridiculously?) the system cached the old icon and used it instead of using the new icon. I don't know. Worse yet, for device 2 = LG Android 5.1, I must clear my app DATA (!) to force it pick up the new icon and be successful. 

E.4. Successful to all devices 1->5
