### ISSUE TITLE
Doesn't work on iOS 9

### ISSUE THREAD

**Issue by graphicgeek** [katzer/cordova-plugin-local-notifications#701]
I'd had reports from some users that my app was crashing after the iOS 9 update when they clicked on the local notifications.

I've updated to the latest version of this plugin hoping it might address the issue, but now the notifications simply aren't working. I schedule them, but nothing happens.

Thinking I might just have something wrong with my code, I installed the example app, but it doesn't work either. When I tap the Single Schedule button, the app freezes up. The log shows this:

Process 934 stopped
* thread #10: tid = 0x4a82a, 0x37767ac6 libobjc.A.dylib`objc_msgSend + 6, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x8000000c)
    frame #0: 0x37767ac6 libobjc.A.dylib`objc_msgSend + 6
libobjc.A.dylib`objc_msgSend:
->  0x37767ac6 <+6>:  ldrh.w r12, [r9, #0xc]
    0x37767aca <+10>: ldr.w  r9, [r9, #0x8]
    0x37767ace <+14>: and.w  r12, r12, r1
    0x37767ad2 <+18>: add.w  r9, r9, r12, lsl #3

This is happening on iOS 9.0.2

**Comment by mr-sparks** [comment]
@graphicgeek The Plugin currently doesn't work right. Everyone is experiencing crash's on their app's in iOS 9. 

Some people got it working by using another Version of the Plugin. 

Either this:

https://github.com/willyboy/cordova-plugin-local-notifications/tree/0c23603

or this:

https://github.com/excendia/cordova-plugin-local-notifications.git

Hope that helps you

**Comment by katzer** [comment]
Hi, does the crash only comes up with a real device? With newest Xcode & iOS 9 SIM at least the example app does not crash.

**Comment by mr-sparks** [comment]
@katzer i'm able to create von scheduled notification. as soon as i set a second one the app crashes. That happens on a real device, as well as on an emulator / xCode...

**Comment by graphicgeek** [comment]
@katzer I haven't tried it in a SIM, only on a device.

**Comment by katzer** [comment]
@mr-sparks, tried it with success. Are you sure that your code isn't doing something wrong?

**Comment by graphicgeek** [comment]
@mr-sparks I got mine to work with this:

https://github.com/willyboy/cordova-plugin-local-notifications

But there seems to be a conflict with the PushPlugin (https://github.com/phonegap/phonegap-plugin-push) because once that's installed, the local notifications stop working. Still investigating.

**Comment by bottasergio** [comment]
@mr-sparks I have just tried on iPad with iOS 9.1 (13B143)  and when notification should appear, app crashed (it disappeared from screen). Plugin: de.appplant.cordova.plugin.local-notification-ios9-fix  version 0.8.2

**Comment by manuelpaulo** [comment]
Some here. Not working on iOS 9.1!

**Comment by gnazarkin** [comment]
+1

**Comment by forzaz** [comment]
Same here, but fixed it with https://github.com/willyboy/cordova-plugin-local-notifications

**Comment by katzer** [comment]
@graphicgeek That has been fixed with v0.8.2

**Comment by daphnawegner** [comment]
Still having the same problem (app crashes) with version 0.8.4
